
["Mothman Config"]
	#The amount of damage the Mothman deals when dashing.
	MM_Damage = 50.0
	#Attempts to spawn Mothman after every tick (20 ticks = 1s.)
	MM_Custom_Spawn_Timer = 400.0
	#How many attempts to find a perfect block location to spawn a Mothman.
	MM_Attempts = 24.0
	#The max X range to attempt the spawning of a Mothman.
	MM_X_range = 128.0
	#The max Y range to attempt the spawning of a Mothman.
	MM_Y_range = 128.0
	#The max Z range to attempt the spawning of a Mothman.
	MM_Z_range = 128.0

